# Generated by Django 3.1.1 on 2020-12-01 01:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_crawler', '0003_auto_20201112_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedsearchhistory',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='advancedsearchhistory',
            name='latest_search',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='advancedsearchhistory',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advancedsearchhistory',
            name='subscribed_frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='latest_search',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='subscribed_frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='advancedsearchhistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
